# Generated by Django 2.2.5 on 2019-12-15 11:42

from django.conf import settings
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('portrait', models.ImageField(default='image/user.png', upload_to='user_portrait')),
                ('std_id', models.CharField(max_length=13, unique=True)),
                ('school', models.CharField(max_length=15)),
                ('points', models.IntegerField(default=0)),
                ('upload_history', models.CharField(max_length=1000)),
                ('download_history', models.CharField(max_length=500)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('abs_url', models.CharField(max_length=60, unique=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=140)),
                ('download_count', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('upload_user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('tag_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('link_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete='CASCADE', to='whursauth.Resource')),
                ('tag_name', models.ForeignKey(on_delete='CASCADE', to='whursauth.TagList')),
            ],
            options={
                'unique_together': {('tag_name', 'resource')},
            },
        ),
    ]
