# Generated by Django 2.2.5 on 2019-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whursauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='std_id',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
