# Generated by Django 2.2.7 on 2019-12-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whursauth', '0002_user_std_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_history',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_history',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
